`ro comment=NA, message=FALSE, cache.path="compare/", tidy=FALSE or`

```{r include=FALSE}
sha <- gsub("^commit ", "", system("git log -n 1", intern=TRUE)[1])
short_sha <- gsub("(^.{10}).*", "\\1", sha)
date <- format(Sys.time(), "%Y-%m-%d")
fig.path = paste("../../../assets/figures/", date, "-", short_sha, "-", sep="")
opts_chunk$set(fig.path=fig.path)
theme_publish <- theme_set(theme_bw(14))
theme_publish <- theme_update(
        # panel.grid.major=theme_blank(),panel.grid.minor=theme_blank(),
        legend.title=theme_blank(), 
        panel.background = theme_rect(fill = "transparent",colour = NA), 
        plot.background = theme_rect(fill = "transparent",colour = NA))
```


```{r}
require(MASS)
require(ggplot2)
require(kernlab)
```

Parameterization-specific


```{r}
X <- seq(-5,5,len=50)
obs <- data.frame(x = c(-4, -3, -1,  0,  2, 3),
                  y = c(-2,  0,  1,  2, -1, -1))
#x <- -5:5
#obs <- data.frame(x = -5:5, y = sin(x) + rnorm(length(x),sd=.1))
l <- 1
sigma_n <- 0.8
```


Radial basis function/Gaussian kernel:

```{r}
  SE <- function(Xi,Xj, l) exp(-0.5 * (Xi - Xj) ^ 2 / l ^ 2)
  cov <- function(X, Y) outer(X, Y, SE, l) 
```


Cholksy method
  
```{r}
  n <- length(obs$x)
  K <- cov(obs$x, obs$x)
  I <-  diag(1, n)

  L <- chol(K + sigma_n^2 * I)
  alpha <- solve(t(L), solve(L, obs$y))
  k_star <- cov(obs$x, X)
  Y <- t(k_star) %*% alpha
  v <- solve(L, k_star)
  Var <- cov(X,X) - t(v) %*% v
  loglik <- -.5 * t(obs$y) %*% alpha - sum(log(diag(L))) - n * log(2 * pi) / 2
```
  
Direct method 

``` {r}
  cov_xx_inv <- solve(K + sigma_n^2*I)
  Ef <- cov(X, obs$x) %*% cov_xx_inv %*% obs$y
  Cf <- cov(X, X) - cov(X, obs$x)  %*% cov_xx_inv %*% cov(obs$x, X)
```

  Direct sequential method, avoids matrix inverse instability
``` {r}
ef <- numeric(length(X))
cf <- matrix(0, nrow=length(X), ncol=length(X))
for(i in 1:length(obs$x)){
  ef <- ef + cov(X, obs$x[i]) * obs$y[i] / as.numeric(cov(obs$x[i],obs$x[i]) + sigma_n^2)
  cf <- cf + cov(X, X) - cov(X, obs$x[i])  %*% cov(obs$x[i], X) / as.numeric(cov(obs$x[i],obs$x[i]) + sigma_n^2)
}
```


``` {r}
ggplot(data.frame(x=X, Ef=Ef, ef=ef))+ geom_point(aes(x,Ef), col='red') + geom_line(aes(x,ef))
````


kernlab method

``` {r}
gp <- gausspr(obs$x, obs$y, kernel="rbfdot", kpar=list(sigma=1/(2*l^2)), fit=FALSE, scaled=FALSE, var=0.8)
y_p <- predict(gp, X)
```


mlegp method

``` {r}
require(mlegp)
out <- mlegp(obs$x, obs$y, nugget = 1)
y_m <- predict(out, as.matrix(X))
```

Compare these results: 

``` {r}
require(reshape2)
df <- data.frame(x = X, Ef = Ef, Y = Y, y_p = y_p, ef = ef, y_m = y_m)
df <- melt(df, id = "x")
ggplot(df)+ geom_jitter(aes(x, value, color = variable)) + geom_point(data = obs, aes(x,y))
````



Compare alpha from Cholesky and alpha from `kernlab` to $K(x,x)^{-1} \vec y$

```{r}
cov_xx_inv %*% obs$y
alpha
alpha(gp)
```

