```{r set-options, echo = FALSE, cache = FALSE, external = TRUE}
opts_chunk$set(external = TRUE, cache = TRUE, cache.path = "myers-cache/")
read_chunk('gaussian-process-control.R')
library(knitcitations)
```


```{r libraries, include=FALSE}
```

```{r graphing-options, include=FALSE}
```

```{r Myer}
```




We use the model of `r citet("10.1126/science.269.5227.1106")`.


```{r sdp-pars}
```

With parameters `r p`. 

```{r sim-obs}
```

```{r lag-data}
```

```{r par-est}
```



```{r gp-fit, dependson="lag-data"}
```

We fit a Gaussian process with 

```{r gp-data, dependson="gp-fit"}
```

```{r gp-plot, dependson="gp-data"}
```


## The transition matrix of the inferred process

```{r persistence-test}
```

```{r gp-F-sim, dependson=c("persistence-test", "gp-data")}
```

```{r par-F-sim, dependson="persistence-test"}
```

```{r F-sim-plot, dependson=c("gp-F-sim", "par-F-sim")}
```



```{r gp-opt, dependson="gp-data"}
```

```{r true-opt}
```

```{r est-opt}
```


```{r policy_plot}
```


```{r othernoise}
```

```{r simulate}
```


```{r tidy}
```


```{r sim-fish}
```


```{r sim-harvest}
```

```{r costs}
```

```{r echo=FALSE, results="asis"}
bibliography("html")
```
