Reed (1979) with Gaussian processes 
========================================================


```{r graphing-options, include=FALSE}
require(pdgControl)
require(nonparametricbayes)
require(reshape2)
require(ggplot2)
require(data.table)
library(kernlab)
opts_knit$set(upload.fun = socialR::notebook.url)
opts_chunk$set(dev.args=list(bg="transparent"), comment=NA, tidy=FALSE)
theme_set(theme_bw())
theme_update(panel.background = element_rect(fill = "transparent",colour = NA),
             plot.background = element_rect(fill = "transparent",colour = NA))
```


```{r results="hide"}
knit("~/Documents/code/nonparametric-bayes/inst/examples/beverton_holt_data.Rmd")
true <- data.frame(x = X, y = sapply(X, f, 0, p))
```

Predict the function over the target grid

```{r}
gp <- gp_fit(obs, X, c(sigma_n=2, tau=10, l=8), "conditional")
plot.gpfit(gp, true)
```


## Stochastic Dynamic programming solution based on the posterior Gaussian process:

```{r}
h_grid <- x_grid
```

GP Solution

```{r}
matrices_gp <- gp_transition_matrix(gp)
opt_gp <- find_dp_optim(matrices_gp, x_grid, h_grid, 20, 0, profit, delta=.01)
```

Optimal solution

```{r}
matrices_true <- f_transition_matrix(f, p, x_grid, h_grid, sigma_g)
opt_true <- find_dp_optim(matrices_true, x_grid, h_grid, 20, 0, profit, delta=.01)
```

Optimal parametric solution in which a parameter is estimated with error

```{r}
k <- 15
A <- 1.5
B <- (A - 1)/k
matrices_estimated <- f_transition_matrix(f, c(A, B), x_grid, h_grid, sigma_g)
opt_estimated <- find_dp_optim(matrices_estimated, x_grid, h_grid, 20, 0, profit, delta=.01)
```


```{r policy_plot}
policies <- melt(data.frame(stock=x_grid, 
                            GP = x_grid[opt_gp$D[,1]], 
                            Exact = x_grid[opt_true$D[,1]],
                            Approx = x_grid[opt_estimated$D[,1]]),
                  id="stock")

policy_plot <- ggplot(policies, aes(stock, stock - value, color=variable)) +
  geom_point() + xlab("stock size") + ylab("escapement") 
policy_plot
```

We can see what happens when we attempt to manage a stock using this:

``` {r othernoise}
z_g <- function() rlnorm(1,0, sigma_g)
````

``` {r  simulate }
set.seed(1)
sim_gp <- ForwardSimulate(f, p, x_grid, h_grid, K, opt_gp$D, z_g, profit=profit)
set.seed(1)
sim_true <- ForwardSimulate(f, p, x_grid, h_grid, K, opt_true$D, z_g, profit=profit)
set.seed(1)
sim_est <- ForwardSimulate(f, p, x_grid, h_grid, K, opt_estimated$D, z_g, profit=profit)
````


```{r}
dat <- list(est = sim_est, gp = sim_gp, true = sim_true)
dat <- melt(dat, id=names(dat[[1]]))
dt <- data.table(dat)
setnames(dt, "L1", "method") 
```

``` {r  simplot}
ggplot(dt) + geom_line(aes(time,fishstock, color=method))
ggplot(dt) + geom_line(aes(time,harvest, color=method))
````

Total Profits

```{r}
c( gp = sum(sim_gp$profit), true = sum(sim_true$profit), est = sum(sim_est$profit))
```

